version: "3.8"

services:
  backend:
    platform: linux/x86_64
    build:
      context: ./backend
    command: npm run start:dev
    container_name: cert-api
    ports:
      - 8000:8000
    expose:
      - "8000"
    volumes:
      - /app/node_modules
      - ./backend:/backend
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
    depends_on:
      - db
    links:
      - db:db
  frontend:
    build:
      context: ./frontend
    platform: linux/x86_64
    container_name: cert-frontend
    stdin_open: true
    command: npm run dev
    volumes:
      - /app/node_modules
      - ./frontend:/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    links:
      - backend:backend
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
    expose:
      - "5432"
    ports:
      - "6432:5432"
volumes:
  frontend:
  backend:
